name: flutter_webrtc
description: Flutter WebRTC plugin for iOS/Android/Desktop/Web, based on GoogleWebRTC.
version: 1.0.0
homepage: https://github.com/cloudwebrtc/flutter-webrtc
environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.22.0"

dependencies:
  collection: ^1.17.0
  dart_webrtc:
    git:
      url: "https://github.com/gutjei/dart-webrtc.git"
      ref: v1.5.3+hotfix.5-audio-capture.2
#    path: "C:\\Users\\ya-ru\\IdeaProjects\\dart-webrtc"
  flutter:
    sdk: flutter
  path_provider: ^2.0.2
  web: ^1.0.0
  webrtc_interface:
    git:
      url: "https://github.com/gutjei/webrtc-interface.git"
      ref: 1.3.0-audio-capture
#    path: "C:\\Users\\ya-ru\\IdeaProjects\\webrtc-interface"

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  lints: ^4.0.0
  pedantic: ^1.11.1
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: com.cloudwebrtc.webrtc
        pluginClass: FlutterWebRTCPlugin
      ios:
        pluginClass: FlutterWebRTCPlugin
      macos:
        pluginClass: FlutterWebRTCPlugin
      windows:
        pluginClass: FlutterWebRTCPlugin
      linux:
        pluginClass: FlutterWebRTCPlugin
      elinux:
        pluginClass: FlutterWebRTCPlugin
